#!/bin/sh

[ $(id -u) -ne 0 ] && {
    echo "Script needs to be run as root"
    exit 1
}

NCS_VID=03e7
NCS_USB_DEVS=$(grep $NCS_VID /sys/bus/usb/devices/*/idVendor | xargs dirname)

for DEV in $NCS_USB_DEVS; do
    echo "Resetting ${NCS_VID}:$(cat $DEV/idProduct) (USB $(cat $DEV/devpath)) $(cat $DEV/product)"
    echo 0 > $DEV/bConfigurationValue
    echo 1 > $DEV/bConfigurationValue
done
